trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  servicenowConnection: '<Your-ServiceNow-Connection-Name>'
  changeRequestSysId: ''
  changeRequestState: ''

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building the project..."
      displayName: 'Build the project'

- stage: Commit
  displayName: 'Commit Stage'
  dependsOn: Build
  jobs:
  - job: CommitJob
    steps:
    - script: echo "Committing the build artifacts..."
      displayName: 'Commit the build artifacts'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Commit
  jobs:
  - job: DeployJob
    steps:
    - task: ServiceNowCreateChangeRequest@2
      inputs:
        connectedServiceName: $(servicenowConnection)
        changeRequestType: 'normal'  # Specify the type of change request (e.g., 'normal', 'emergency')
        changeRequestDetails: |
          {
            "short_description": "Deployment
